
init:
  - git config --global core.autocrlf input

clone_folder: C:\projects\ukncbtl-utils
shallow_clone: true

matrix:
  fast_finish: false

platform:
  - Win32

configuration:
  - Debug
  - Release

# See https://www.appveyor.com/docs/windows-images-software/
environment:
  matrix:
    - toolchain: msvc13
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - toolchain: msvc15
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - toolchain: msvc17
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    - toolchain: msvc19
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019

build:
  project: UkncbtlUtils-VS2013.sln

